# Generated by Django 2.2.4 on 2019-08-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='raters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('gender', models.IntegerField()),
                ('Workflow', models.IntegerField()),
            ],
        ),
    ]
