# Generated by Django 2.2.4 on 2019-08-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raters_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(max_length=50)),
                ('Category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='workflows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(max_length=50)),
                ('version_number', models.IntegerField()),
            ],
        ),
    ]
